<section class="om-detail om-order-console">
  <header class="oc-header">
    <div class="oc-header-main">
      <div class="oc-nav">
        <a href="?controller=orders" title="Wróć do listy" aria-label="Wróć do listy"><i class="bi bi-arrow-left"></i></a>
        <button type="button" title="Historia zamówienia" aria-label="Historia zamówienia" data-order-section="om-history"><i class="bi bi-clock-history"></i></button>
        {if $canWrite}<form method="post" action="?controller=orders&action=save" data-double-confirm="Usunąć to zamówienie? Tej operacji nie można cofnąć.||Potwierdź jeszcze raz: zamówienie #{$detail.id}, jego przesyłki i historia zostaną trwale usunięte. Jeśli pochodzi z marketplace, może pojawić się ponownie przy kolejnej synchronizacji — najpierw wstrzymaj import konta w zakładce Konta, jeśli tego nie chcesz."><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="delete_order"><input type="hidden" name="order_id" value="{$detail.id}"><button type="submit" class="oc-nav-danger" title="Usuń zamówienie" aria-label="Usuń zamówienie"><i class="bi bi-trash"></i></button></form>{/if}
      </div>
      <div class="oc-identity">
        <div class="oc-title-row"><h1>Zamówienie <strong>#{$detail.id}</strong></h1><span class="om-market {$detail.platform|escape}">{$detail.platform|escape}</span><span class="om-document-choice {if $detail.details.document_preference eq 'invoice'}invoice{else}receipt{/if}"><i class="bi {if $detail.details.document_preference eq 'invoice'}bi-file-earmark-text{else}bi-receipt{/if}"></i> {if $detail.details.document_preference eq 'invoice'}Faktura{else}Paragon{/if}</span>{if $detail.details.cash_on_delivery}<span class="om-cod-badge"><i class="bi bi-cash-coin"></i> Pobranie</span>{/if}</div>
        <p><span><i class="bi bi-calendar3"></i> {$detail.ordered_at|escape} UTC</span><span><i class="bi bi-shop"></i> {$detail.account_name|escape}</span>{if $detail.source_order_url|default:'' neq ''}<a class="om-source-order-link" href="{$detail.source_order_url|escape}" target="_blank" rel="noopener noreferrer" title="Otwórz zamówienie w {$detail.platform|escape}"><i class="bi bi-link-45deg"></i> {$detail.external_id|escape}<i class="bi bi-box-arrow-up-right" aria-hidden="true"></i></a>{else}<span><i class="bi bi-link-45deg"></i> {$detail.external_id|escape}</span>{/if}</p>
      </div>
    </div>
    <div class="oc-header-summary">
      <div class="oc-total"><span>Wartość</span><strong>{($detail.total_cents/100)|string_format:'%.2f'} {$detail.currency|escape}</strong></div>
      <span class="oc-payment-state {if $detail.details.cash_on_delivery}is-cod{elseif $detail.paid}is-paid{else}is-due{/if}"><i class="bi {if $detail.details.cash_on_delivery}bi-cash-coin{elseif $detail.paid}bi-check-circle-fill{else}bi-clock{/if}"></i> {if $detail.details.cash_on_delivery}Do pobrania{elseif $detail.paid}Opłacone{else}Do weryfikacji{/if}</span>
      <div class="oc-actions" aria-label="Akcje zamówienia"><button type="button" data-order-section="om-data-grid"><i class="bi bi-pencil-square"></i><span>Dane</span></button><button type="button" data-order-section="om-shipping"><i class="bi bi-box-seam"></i><span>Przesyłka</span></button><button type="button" data-order-section="om-documents"><i class="bi bi-receipt"></i><span>Dokumenty</span></button></div>
    </div>
  </header>

  <form id="om-order-settings" class="oc-commandbar" method="post" action="?controller=orders&action=save" data-auto-order-settings>
    <input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="order"><input type="hidden" name="order_id" value="{$detail.id}">
    <label class="oc-status" style="--status-color:{$detail.color|escape}"><span>Status</span><select name="status_id">{foreach $statuses as $s}<option value="{$s.id}" {if $detail.status_id eq $s.id}selected{/if}>{$s.name|escape}</option>{/foreach}</select></label>
    <label class="oc-tags"><span>Tagi</span><input name="tags" value="{$detail.tags|escape}" placeholder="np. priorytet, prezent"></label>
    <label class="oc-note"><span>Notatka wewnętrzna</span><textarea name="note" rows="1" placeholder="Dodaj notatkę…">{$detail.note|escape}</textarea></label>
    {if $canWrite}<span class="oc-autosave" data-autosave-state><i class="bi bi-cloud-check"></i> Zapis automatyczny</span>{/if}
  </form>

  {if $canWrite && !($issuedDocuments.receipt|default:false)}<form id="om-issue-receipt" method="post" action="?controller=orders&action=save" hidden><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="quick_document"><input type="hidden" name="order_id" value="{$detail.id}"><input type="hidden" name="kind" value="receipt"><input type="hidden" name="request_key" value="{$documentKey|escape}a"></form>{/if}
  {if $canWrite && !($issuedDocuments.invoice|default:false)}<form id="om-issue-invoice" method="post" action="?controller=orders&action=save" hidden><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="quick_document"><input type="hidden" name="order_id" value="{$detail.id}"><input type="hidden" name="kind" value="invoice"><input type="hidden" name="request_key" value="{$documentKey|escape}b"></form>{/if}

  <form id="om-inline-data" class="oc-order-form" method="post" action="?controller=orders&action=save" data-inline-order-form>
    <input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="order_details"><input type="hidden" name="order_id" value="{$detail.id}">
    <div id="om-data-grid" class="oc-data-grid">
      <article class="oc-card oc-buyer-card">
        <div class="oc-card-head"><span class="oc-icon"><i class="bi bi-person"></i></span><div><small>KLIENT</small><h2>Kupujący</h2></div><span class="oc-card-hint">{$detail.details.raw.buyer.login|default:'—'|escape}</span></div>
        <div class="oc-fields"><label class="oc-wide">Imię i nazwisko / firma<input name="buyer_name" value="{$detail.buyer_name|escape}" required></label><label>E-mail<input type="email" name="email" value="{$detail.email|escape}"></label><label>Telefon<input name="phone" value="{$detail.phone|escape}"></label><label class="oc-wide">Wiadomość kupującego<textarea name="buyer_note" rows="2">{$detail.details.buyer_note|escape}</textarea></label><label class="oc-wide">Dokument sprzedaży<select name="document_preference" data-document-preference><option value="receipt" {if $detail.details.document_preference eq 'receipt'}selected{/if}>Paragon</option><option value="invoice" {if $detail.details.document_preference eq 'invoice'}selected{/if}>Faktura</option></select></label></div>
      </article>
      <article class="oc-card oc-delivery-card">
        <div class="oc-card-head"><span class="oc-icon"><i class="bi bi-geo-alt"></i></span><div><small>ODBIORCA</small><h2>Dostawa</h2></div><span class="oc-card-hint">{$detail.shipping_address.country|default:'PL'|escape}</span></div>
        <div class="oc-delivery-method"><span><small>Metoda</small><strong>{$detail.details.delivery|default:'Brak danych'|escape}</strong></span>{if $detail.details.pickup}<span><small>Punkt</small><strong>{$detail.details.pickup|escape}</strong></span>{/if}<span><small>Koszt</small><strong>{($detail.details.shipping_cents/100)|string_format:'%.2f'} {$detail.currency|escape}</strong></span></div>
        <div class="oc-fields"><label class="oc-wide">Metoda dostawy<input name="delivery" value="{$detail.details.delivery|escape}"></label><label>Punkt odbioru<input name="pickup" value="{$detail.details.pickup|escape}"></label><label>Koszt dostawy<input inputmode="decimal" name="shipping_price" value="{($detail.details.shipping_cents/100)|string_format:'%.2f'}"></label><label class="oc-wide">Imię i nazwisko<input name="shipping_name" value="{$detail.shipping_address.name|escape}"></label><label class="oc-wide">Ulica<input name="shipping_street" value="{$detail.shipping_address.street|escape}"></label><label>Numer<input name="shipping_building" value="{$detail.shipping_address.building|escape}"></label><label>Kod pocztowy<input name="shipping_postal_code" value="{$detail.shipping_address.postal_code|escape}"></label><label>Miasto<input name="shipping_city" value="{$detail.shipping_address.city|escape}"></label><label>Kraj<input name="shipping_country" maxlength="2" value="{$detail.shipping_address.country|default:'PL'|escape}"></label><label>Telefon<input name="shipping_phone" value="{$detail.shipping_address.phone|escape}"></label><label>E-mail<input type="email" name="shipping_email" value="{$detail.shipping_address.email|escape}"></label></div>
      </article>
      <article class="oc-card oc-payment-card">
        <div class="oc-card-head"><span class="oc-icon"><i class="bi bi-credit-card"></i></span><div><small>ROZLICZENIE</small><h2>Płatność</h2></div><span class="oc-card-hint">{$detail.currency|escape}</span></div>
        <div class="oc-payment-hero"><div><span>Razem</span><strong>{($detail.total_cents/100)|string_format:'%.2f'} {$detail.currency|escape}</strong></div><div><span>{if $detail.details.cash_on_delivery}Do pobrania{else}Pozostało{/if}</span><strong class="{if $detail.details.amount_due_cents gt 0}is-due{else}is-paid{/if}">{($detail.details.amount_due_cents/100)|string_format:'%.2f'} {$detail.currency|escape}</strong></div></div>
        <div class="oc-fields"><label class="oc-wide">Metoda płatności<input name="payment_method" value="{$detail.details.payment_method|escape}"></label><label>Wartość<input inputmode="decimal" name="total" value="{($detail.total_cents/100)|string_format:'%.2f'}" required></label><label>Zapłacono<input inputmode="decimal" name="amount_paid" value="{($detail.details.amount_paid_cents/100)|string_format:'%.2f'}" required></label><label>Waluta<input name="currency" maxlength="3" value="{$detail.currency|escape}" required></label><label class="oc-check"><input type="checkbox" name="paid" value="1" {if $detail.paid}checked{/if}> Opłacone</label><label class="oc-check oc-wide"><input type="checkbox" name="cash_on_delivery" value="1" {if $detail.details.cash_on_delivery}checked{/if}> Płatność za pobraniem</label></div>
        <div class="oc-doc-actions"><div><span>Paragon</span>{if $issuedDocuments.receipt|default:false}<a target="_blank" rel="noopener" href="?controller=orders&action=printdocument&id={$issuedDocuments.receipt.id}"><i class="bi bi-check-circle-fill"></i> {$issuedDocuments.receipt.number|escape}</a>{elseif $canWrite}<button type="submit" form="om-issue-receipt" class="receipt"><i class="bi bi-receipt"></i> Wystaw</button>{else}<em>Brak</em>{/if}</div><div><span>Faktura</span>{if $issuedDocuments.invoice|default:false}<a target="_blank" rel="noopener" href="?controller=orders&action=printdocument&id={$issuedDocuments.invoice.id}"><i class="bi bi-check-circle-fill"></i> {$issuedDocuments.invoice.number|escape}</a>{elseif $canWrite}<button type="submit" form="om-issue-invoice" class="invoice"><i class="bi bi-file-earmark-text"></i> Wystaw</button>{else}<em>Brak</em>{/if}</div></div>
        {if $canWrite && !($issuedDocuments.receipt|default:false)}<label>Seria paragonu<select name="series_id" form="om-issue-receipt">{foreach $series as $s}{if $s.kind eq 'receipt'}<option value="{$s.id}">{$s.name|escape} — {foreach $printFiscalPrinters as $printer}{if $printer.id eq $s.effective_printer_id}{$printer.name|escape} ({if $printer.environment eq 'production'}PRODUKCJA{else}SANDBOX{/if}){/if}{/foreach}{if !$s.effective_printer_id}bez automatycznego druku{/if}</option>{/if}{/foreach}</select></label>{/if}
        <p class="om-muted">Drukarka zależy od wybranej serii paragonu. <a href="?controller=orders&tab=documents">Edytuj serie i przypisania</a>.</p>
        <details class="om-invoice-fields oc-invoice-fields" data-invoice-fields {if $detail.details.document_preference ne 'invoice'}hidden{/if}><summary class="oc-subhead"><i class="bi bi-building"></i> Dane do faktury <span>pokaż i edytuj</span><i class="bi bi-chevron-down"></i></summary><div class="oc-fields"><label class="oc-wide">Nazwa / firma<input name="invoice_name" value="{$detail.details.invoice_form.name|default:''|escape}"></label><label class="oc-wide">Firma<input name="invoice_company" value="{$detail.details.invoice_form.company|default:''|escape}"></label><label class="oc-wide">NIP<input name="invoice_nip" value="{$detail.details.invoice_form.nip|default:''|escape}"></label><label class="oc-wide">Ulica<input name="invoice_street" value="{$detail.details.invoice_form.street|default:''|escape}"></label><label>Numer<input name="invoice_building" value="{$detail.details.invoice_form.building|default:''|escape}"></label><label>Kod<input name="invoice_postal_code" value="{$detail.details.invoice_form.postal_code|default:''|escape}"></label><label>Miasto<input name="invoice_city" value="{$detail.details.invoice_form.city|default:''|escape}"></label><label>Kraj<input name="invoice_country" maxlength="2" value="{$detail.details.invoice_form.country|default:'PL'|escape}"></label></div></details>
      </article>
    </div>

    <section class="oc-card oc-products">
      <div class="oc-section-head"><div><small>POZYCJE ZAMÓWIENIA</small><h2>Produkty</h2></div><span>{$detail.details.items|count} pozycji</span></div>
      <div class="oc-products-table"><div class="oc-product-row oc-product-head"><span>Produkt</span><span>SKU</span><span>Ilość</span><span>VAT</span><span>Cena</span><span>Wartość</span></div>{foreach $detail.details.items as $i=>$item}<div class="oc-product-row om-inline-product-row"><span class="oc-product-name"><span class="om-product-thumb">{if $item.image_url}<img src="{$item.image_url|escape}" alt="" loading="lazy" data-product-image>{else}<i class="bi bi-box"></i>{/if}</span><input name="items[{$i}][name]" value="{$item.name|escape}" required aria-label="Nazwa produktu"></span><input name="items[{$i}][sku]" value="{$item.sku|escape}" aria-label="SKU"><input type="number" min="0" step="1" name="items[{$i}][quantity]" value="{$item.quantity}" required aria-label="Ilość" data-line-quantity><select name="items[{$i}][vat]" aria-label="VAT">{foreach ['23','8','5','0','zw','np'] as $v}<option value="{$v}" {if ($item.vat|default:'23') eq $v}selected{/if}>{$v}{if $v ne 'zw' and $v ne 'np'}%{/if}</option>{/foreach}</select><input inputmode="decimal" name="items[{$i}][price]" value="{($item.unit_cents/100)|string_format:'%.2f'}" required aria-label="Cena brutto" data-line-price><strong data-line-total>{($item.unit_cents*$item.quantity/100)|string_format:'%.2f'} {$detail.currency|escape}</strong></div>{/foreach}{if $detail.details.shipping_cents gt 0}<div class="oc-product-row oc-product-shipping"><span class="oc-product-name"><span class="om-product-thumb"><i class="bi bi-truck"></i></span><strong>Dostawa — {$detail.details.delivery|default:'przesyłka'|escape}</strong></span><span>{$detail.details.pickup|default:'—'|escape}</span><span>1</span><span>{$documentDefaults.vat|default:'23'|escape}%</span><span>{($detail.details.shipping_cents/100)|string_format:'%.2f'} {$detail.currency|escape}</span><strong>{($detail.details.shipping_cents/100)|string_format:'%.2f'} {$detail.currency|escape}</strong></div>{/if}</div>
      <div class="oc-savebar"><p><i class="bi bi-shield-check"></i> Zapisane dane nie zostaną nadpisane przy synchronizacji.</p><div class="oc-totals"><span><small>Razem</small><strong data-order-total>{($detail.total_cents/100)|string_format:'%.2f'} {$detail.currency|escape}</strong></span><span class="is-paid"><small>Zapłacono</small><strong data-order-paid>{($detail.details.amount_paid_cents/100)|string_format:'%.2f'} {$detail.currency|escape}</strong></span><span class="{if $detail.details.amount_due_cents gt 0}is-due{/if}" data-order-due-box><small data-order-due-label>{if $detail.details.cash_on_delivery}Do pobrania{else}Do zapłaty{/if}</small><strong data-order-due>{($detail.details.amount_due_cents/100)|string_format:'%.2f'} {$detail.currency|escape}</strong></span></div>{if $canWrite}<button class="om-btn om-primary"><i class="bi bi-check2"></i> Zapisz zmiany</button>{/if}</div>
    </section>
  </form>

  <details id="om-shipping" class="oc-card oc-disclosure oc-shipping" open>
    <summary><span class="oc-summary-icon"><i class="bi bi-box-seam"></i></span><span><small>REALIZACJA</small><strong>Przesyłki</strong></span><span class="oc-summary-meta">{$orderShipments|count} utworzonych</span><i class="bi bi-chevron-down oc-chevron"></i></summary>
    <div class="oc-disclosure-body">
      {if $canWrite and ($orderShipments|count)}{include file='orders/order_label_print.tpl'}{/if}
      {foreach $orderShipments as $p}
        <article class="om-existing-shipment oc-shipment-record is-{$p.presentation.status_tone|escape} {if $p.state eq 'CANCELLED' or $p.state eq 'CANCELED' or $p.state eq 'ANULOWANO'}is-cancelled{/if}">
          <div class="oc-shipment-record-main">
            <div class="oc-shipment-record-top">
              <span class="oc-shipment-provider-icon"><i class="bi bi-box-seam"></i></span>
              <span class="oc-shipment-account"><small>OPERATOR WYSYŁKI</small><strong>{$p.carrier|escape}</strong></span>
              <span class="oc-carrier-status is-{$p.presentation.status_tone|escape}"><i class="bi bi-broadcast-pin"></i><span><small>STATUS U PRZEWOŹNIKA</small><strong>{$p.presentation.status_label|escape}</strong></span></span>
            </div>
            <div class="oc-shipment-facts">
              <span><small>Metoda dostawy</small><strong>{$p.presentation.delivery_method|escape}</strong></span>
              <span><small>Przewoźnik</small><strong>{$p.presentation.carrier|escape}</strong></span>
              <span><small>Usługa</small><strong>{$p.presentation.service|escape}</strong>{if $p.presentation.service_code}<em>{$p.presentation.service_code|escape}</em>{/if}</span>
            </div>
            <div class="oc-shipment-foot">
              <span class="oc-tracking-number"><i class="bi bi-upc-scan"></i><small>Numer przesyłki</small><strong>{$p.tracking|escape}</strong></span>
              <span><i class="bi bi-calendar3"></i> Utworzono {$p.created_at|escape} UTC</span>
              {if $p.presentation.status_updated_at}<span title="{$p.presentation.status_updated_at|escape}"><i class="bi bi-arrow-repeat"></i> Status z {$p.presentation.status_updated_at|escape}</span>{/if}
              {if $p.cod_amount_cents gt 0}<strong><i class="bi bi-cash-coin"></i> Pobranie: {($p.cod_amount_cents/100)|string_format:'%.2f'} {$p.shipment_currency|escape}</strong>{else}<span><i class="bi bi-cash"></i> Bez pobrania</span>{/if}
            </div>
            <div class="oc-source-publication is-{$p.presentation.source_publication.state|default:'new'|escape}">
              <span><small>WYSŁANO DO {$detail.platform|upper|escape}</small><strong>{if $p.presentation.source_publication.sent_at_label}<i class="bi bi-check-circle-fill"></i> Tak · {$p.presentation.source_publication.sent_at_label|escape}{elseif $p.presentation.source_publication.attempted_at_label}<i class="bi bi-x-circle"></i> Nie · próba {$p.presentation.source_publication.attempted_at_label|escape}{else}<i class="bi bi-circle"></i> Nie{/if}</strong></span>
              <span><small>ŹRÓDŁO ODEBRAŁO</small><strong>{if $p.presentation.source_publication.received_at_label}<i class="bi bi-check-circle-fill"></i> Tak · {$p.presentation.source_publication.received_at_label|escape}{elseif $p.presentation.source_publication.attempted_at_label}<i class="bi bi-x-circle"></i> Nie — odrzucono{else}<i class="bi bi-circle"></i> Nie{/if}</strong></span>
              {if $p.presentation.source_publication.carrier_name|default:''}<span><small>PRZEKAZANY PRZEWOŹNIK</small><strong>{$p.presentation.source_publication.carrier_name|escape}</strong></span>{/if}
              {if $p.presentation.source_publication.error|default:''}<p><i class="bi bi-exclamation-triangle"></i> {$p.presentation.source_publication.error|escape}</p>{/if}
            </div>
            {if $p.presentation.status_description}<p class="oc-shipment-status-description">{$p.presentation.status_description|escape}</p>{/if}
          </div>
          <div class="om-actions oc-shipment-actions">{if $canWrite}<form method="post" action="index.php?controller=orders&action=save"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="refresh_shipment"><input type="hidden" name="order_id" value="{$detail.id}"><input type="hidden" name="shipment_id" value="{$p.id}"><button class="om-btn om-small"><i class="bi bi-arrow-repeat"></i> Odśwież status</button></form>{if $detail.platform ne 'manual'}<form class="oc-source-publish-form" method="post" action="index.php?controller=orders&action=save" data-source-shipment><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="publish_shipment"><input type="hidden" name="order_id" value="{$detail.id}"><input type="hidden" name="shipment_id" value="{$p.id}"><select name="source_carrier" required aria-label="Przewoźnik przekazywany do źródła"><option value="">Przewoźnik…</option>{foreach $sourceCarrierOptions as $code=>$name}<option value="{$code|escape}" {if $p.presentation.source_publication.carrier_code|default:'' eq $code}selected{/if}>{$name|escape}</option>{/foreach}</select><input name="source_carrier_other" maxlength="100" placeholder="Nazwa przewoźnika" value="{if $p.presentation.source_publication.carrier_code|default:'' eq 'other'}{$p.presentation.source_publication.carrier_name|escape}{/if}" hidden data-other-carrier><button class="om-btn om-small om-primary"><i class="bi bi-cloud-arrow-up"></i> Wyślij nr do źródła</button></form>{/if}{if $p.carrier_provider eq 'apaczka' and $p.state ne 'CANCELLED' and $p.state ne 'CANCELED' and $p.state ne 'ANULOWANO'}<form method="post" action="index.php?controller=orders&action=save" data-confirm-action="Anulować tę przesyłkę w Apaczce? Po anulowaniu pozostanie w historii z czerwonym statusem."><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="cancel_shipment"><input type="hidden" name="order_id" value="{$detail.id}"><input type="hidden" name="shipment_id" value="{$p.id}"><button class="om-btn om-small om-danger">Anuluj</button></form>{/if}<form method="post" action="index.php?controller=orders&action=save" data-confirm-action="Usunąć tylko wpis z CRM? Przesyłka NIE zostanie anulowana u przewoźnika."><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="delete_shipment"><input type="hidden" name="order_id" value="{$detail.id}"><input type="hidden" name="shipment_id" value="{$p.id}"><button class="om-btn om-small om-danger-outline">Usuń z CRM</button></form>{/if}{if $p.state ne 'CANCELLED' and $p.state ne 'CANCELED' and $p.state ne 'ANULOWANO'}<a class="om-btn om-small" target="_blank" rel="noopener" href="index.php?controller=orders&action=labelshipment&id={$p.id}"><i class="bi bi-file-earmark-pdf"></i> Etykieta PDF</a>{if $canWrite}{include file='orders/label_print.tpl'}{/if}{/if}</div>
        </article>
      {/foreach}
      {if $canWrite && $carrierAccounts|count}<details class="oc-shipment-composer" {if ($orderShipments|count) eq 0}open{/if}><summary><i class="bi bi-plus-lg"></i> Utwórz {if $orderShipments|count}kolejną {/if}przesyłkę <span>Dane odbiorcy i paczki są już uzupełnione</span></summary><form class="om-smart-shipment-form" method="post" action="index.php?controller=orders&action=save" data-confirm-shipment data-smart-shipment><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="create_shipment"><input type="hidden" name="order_id" value="{$detail.id}"><input type="hidden" name="request_key" value="{$documentKey|escape}">
        <div class="om-shipping-choice"><label>1. Konto nadawcze<select name="carrier_account_id" required data-carrier-select><option value="">Wybierz konto</option>{foreach $carrierAccounts as $c}{if $c.enabled}<option value="{$c.id}" data-provider="{$c.provider|escape}" {if $shipmentSuggestion.carrier_account_id eq $c.id}selected{/if}>{$c.name|escape}</option>{/if}{/foreach}</select></label><p><i class="bi bi-stars"></i> {$shipmentSuggestion.reason|default:'Wybierz aktywne konto nadawcze'|escape}</p></div>
        <div class="om-shipping-choice"><label>2. Przewoźnik i usługa<select name="shipping_service" data-shipping-service data-default-inpost="{$shipmentSuggestion.service|escape}" data-default-apaczka="{$shippingDefaults.apaczka_service_id|default:0}" data-delivery="{$detail.details.delivery|escape}" data-cash-on-delivery="{$detail.details.cash_on_delivery|default:0}"><option value="">Wybierz konto — pobiorę dostępne usługi</option></select></label><p data-shipping-service-status><i class="bi bi-arrow-repeat"></i> Lista zależy od wybranego konta</p></div>
        <div class="om-shipping-choice"><label>3. Rozmiar paczki<select data-package-preset><option value="small" data-length="{$shippingDefaults.presets.small.length|default:23}" data-width="{$shippingDefaults.presets.small.width|default:16}" data-height="{$shippingDefaults.presets.small.height|default:10}" data-weight="{$shippingDefaults.presets.small.weight|default:0.5}" {if $shipmentSuggestion.preset eq 'small'}selected{/if}>Mała</option><option value="medium" data-length="{$shippingDefaults.presets.medium.length|default:30}" data-width="{$shippingDefaults.presets.medium.width|default:20}" data-height="{$shippingDefaults.presets.medium.height|default:15}" data-weight="{$shippingDefaults.presets.medium.weight|default:1}" {if $shipmentSuggestion.preset eq 'medium'}selected{/if}>Średnia</option><option value="large" data-length="{$shippingDefaults.presets.large.length|default:40}" data-width="{$shippingDefaults.presets.large.width|default:30}" data-height="{$shippingDefaults.presets.large.height|default:20}" data-weight="{$shippingDefaults.presets.large.weight|default:2}" {if $shipmentSuggestion.preset eq 'large'}selected{/if}>Duża</option><option value="custom">Własne wymiary</option></select></label><p><i class="bi bi-magic"></i> Podpowiedź na podstawie liczby produktów</p></div>
        <div class="om-package-fields"><label>Długość <span>cm</span><input type="number" name="length" min="1" max="400" step="1" value="{$shipmentSuggestion.package.length|default:30}" required data-package-field="length"></label><label>Szerokość <span>cm</span><input type="number" name="width" min="1" max="400" step="1" value="{$shipmentSuggestion.package.width|default:20}" required data-package-field="width"></label><label>Wysokość <span>cm</span><input type="number" name="height" min="1" max="400" step="1" value="{$shipmentSuggestion.package.height|default:15}" required data-package-field="height"></label><label>Waga <span>kg</span><input type="number" name="weight" min="0.01" max="1000" step="0.01" value="{$shipmentSuggestion.package.weight|default:1}" required data-package-field="weight"></label></div>
        <div class="om-provider-options"><div class="om-cod-control"><label class="om-check"><input type="checkbox" name="cash_on_delivery" value="1" data-cod-toggle {if $detail.details.cash_on_delivery|default:0}checked{/if}> Pobranie</label><label class="om-cod-amount">Kwota pobrania <span>{$detail.currency|escape}</span><input type="number" name="cod_amount" min="0.01" step="0.01" value="{(($detail.details.amount_due_cents|default:$detail.total_cents)/100)|string_format:'%.2f'}" data-cod-amount></label></div></div><div class="om-provider-options"><label>Zawartość przesyłki<input name="shipment_content" maxlength="180" value="{$shippingDefaults.content|default:'Towar'|escape}" required><small>Automatycznie dopiszę: zamówienie ID {$detail.id}</small></label></div>
        <details class="om-shipping-advanced"><summary><i class="bi bi-person-check"></i> Sprawdź odbiorcę i dane zaawansowane</summary><div class="om-advanced-grid"><label>Odbiorca<input name="receiver_name" value="{$detail.shipping_address.name|escape}" required></label><label>E-mail<input type="email" name="receiver_email" value="{$detail.shipping_address.email|escape}" required></label><label>Telefon<input name="receiver_phone" value="{$detail.shipping_address.phone|escape}" required></label><label>Ulica<input name="receiver_street" value="{$detail.shipping_address.street|escape}" required></label><label>Nr budynku / lokalu<input name="receiver_building" value="{$detail.shipping_address.building|escape}" required></label><label>Kod pocztowy<input name="receiver_postal_code" value="{$detail.shipping_address.postal_code|escape}" required></label><label>Miasto<input name="receiver_city" value="{$detail.shipping_address.city|escape}" required></label><label>Kraj<input name="receiver_country" value="{$detail.shipping_address.country|escape}" maxlength="2" required></label></div></details><div class="om-shipping-submit"><div><strong data-shipping-price>Wybierz usługę Apaczka, aby obliczyć cenę</strong><span>Wycena uwzględnia usługę, wymiary, wagę i pobranie.</span></div><button class="om-btn om-primary"><i class="bi bi-truck"></i> Utwórz przesyłkę</button></div>
      </form></details>{elseif $canWrite}<div class="om-carrier-pending"><i class="bi bi-plug"></i><strong>Najpierw podłącz operatora przesyłek</strong><p>Konfigurację znajdziesz w Centrum zamówień → Przesyłki i presety.</p></div>{/if}
    </div>
  </details>

  <details id="om-documents" class="oc-card oc-disclosure oc-documents"><summary><span class="oc-summary-icon"><i class="bi bi-receipt"></i></span><span><small>SPRZEDAŻ</small><strong>Dokumenty i korekty</strong></span><span class="oc-summary-meta">{$orderDocs|count} wystawionych</span><i class="bi bi-chevron-down oc-chevron"></i></summary><div class="oc-disclosure-body"><div class="om-document-workflow"><div class="om-document-actions"><h3>Dokumenty sprzedaży</h3><p>Paragon lub fakturę wystawisz w karcie „Płatność” powyżej. Po wystawieniu przycisk zostanie zastąpiony numerem dokumentu.</p></div><div class="om-document-list"><h3>Wystawione dokumenty</h3>{foreach $orderDocs as $d}<a target="_blank" rel="noopener" href="?controller=orders&action=printdocument&id={$d.id}"><i class="bi bi-file-earmark-pdf"></i><span><strong>{$d.number|escape}</strong><small>{$d.created_at|escape} UTC</small></span><i class="bi bi-box-arrow-up-right"></i></a>{foreachelse}<div class="om-doc-empty"><i class="bi bi-file-earmark"></i> Brak dokumentów</div>{/foreach}</div></div><details class="om-correction-box"><summary><i class="bi bi-arrow-counterclockwise"></i> Korekta / zmiana wystawionego dokumentu</summary><p>Oryginał pozostaje w historii, a aktualne dane i pozycje zamówienia trafią do korekty.</p>{if $canWrite && $orderDocs|count}<form method="post" action="?controller=orders&action=save"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="quick_correction"><input type="hidden" name="order_id" value="{$detail.id}"><input type="hidden" name="request_key" value="{$documentKey|escape}"><label>Dokument do zmiany<select name="parent_id" required><option value="">Wybierz dokument</option>{foreach $orderDocs as $d}{if $d.kind eq 'invoice' or $d.kind eq 'receipt'}<option value="{$d.id}">{$d.number|escape}</option>{/if}{/foreach}</select></label><label>Powód korekty<input name="reason" required placeholder="Np. zmiana danych nabywcy lub zwrot"></label><button class="om-btn om-primary">Wystaw korektę z aktualnych danych</button></form>{else}<span class="om-muted">Korektę wystawisz po utworzeniu pierwszego paragonu lub faktury.</span>{/if}</details></div></details>
  <details id="om-history" class="oc-card oc-disclosure oc-history"><summary><span class="oc-summary-icon"><i class="bi bi-clock-history"></i></span><span><small>AKTYWNOŚĆ</small><strong>Historia i automatyzacje</strong></span><span class="oc-summary-meta">{$events|count} wpisów</span><i class="bi bi-chevron-down oc-chevron"></i></summary><div class="oc-disclosure-body">{if $canWrite}<form method="post" action="?controller=orders&action=save"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="preview_rule"><input type="hidden" name="order_id" value="{$detail.id}"><button class="om-btn">Testuj dopasowanie reguł importu</button></form>{/if}<div class="om-timeline">{foreach $events as $event}<article><small>{$event.created_at|escape} UTC · {$event.actor|escape}</small><p>{$event.message|escape}</p></article>{/foreach}</div></div></details>
</section>
