<div class="om-section-heading"><div><h2>Dokumenty sprzedaży</h2><p>Oddzielne serie, trwałe kopie dokumentów, korekty i wydruki A4.</p></div><span class="om-chip">Dokument A4 pozostaje niefiskalny · fiskalizacja zależy od drukarki</span></div>
<section class="om-panel om-pad om-bottom">
  <h3>Automatyczny druk paragonów</h3>
  <p class="om-muted">Przypisz drukarkę osobno do każdej serii paragonów poniżej. Po wystawieniu paragon trafi do kolejki przypisanej drukarki; faktury i korekty nie są wysyłane. Urządzenia dodasz w <a href="?controller=orders&tab=printing">Drukowaniu</a>.</p>
  <p class="om-muted om-top"><strong>PRODUKCJA</strong> rejestruje sprzedaż na urządzeniu fiskalnym. <strong>SANDBOX</strong> drukuje oznaczony paragon niefiskalny na Posnet i nie rejestruje sprzedaży. Tryb ustawisz przy drukarce w zakładce Drukowanie.</p>
  {if !$printFiscalPrinters}<p class="om-muted">Nie ma jeszcze drukarki Posnet. Dodaj ją w zakładce Drukowanie i włącz przed przypisaniem.</p>{/if}
</section>
<div class="om-two-col">
<section class="om-panel om-pad"><h3>Dane sprzedawcy</h3><form class="om-form" method="post" action="?controller=orders&action=save"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="seller"><input type="hidden" name="tab" value="documents"><label>Nazwa firmy<input name="name" value="{$seller.name|escape}" required></label><label>NIP<input name="nip" value="{$seller.nip|escape}" required></label><label>Adres<textarea name="address" required>{$seller.address|escape}</textarea></label><label>Rachunek bankowy<input name="bank" value="{$seller.bank|escape}"></label>{if $canWrite}<button class="om-btn om-primary">Zapisz dane sprzedawcy</button>{/if}</form><p class="om-muted om-top">Zmiana danych nie zmienia wcześniej zapisanych dokumentów. Wystawianie odbywa się w szczegółach zamówienia.</p></section>
<section class="om-panel om-pad"><h3>Serie numeracji</h3>
{foreach $series as $s}
  <form class="om-form om-top" method="post" action="?controller=orders&action=save">
    <input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="series_update"><input type="hidden" name="tab" value="documents"><input type="hidden" name="series_id" value="{$s.id}">
    <label>Nazwa serii<input name="name" value="{$s.name|escape}" maxlength="100" required></label>
    <label>Typ<select name="kind"><option value="invoice" {if $s.kind eq 'invoice'}selected{/if}>Faktura</option><option value="receipt" {if $s.kind eq 'receipt'}selected{/if}>Paragon</option><option value="invoice_correction" {if $s.kind eq 'invoice_correction'}selected{/if}>Korekta faktury</option><option value="receipt_correction" {if $s.kind eq 'receipt_correction'}selected{/if}>Korekta paragonu</option></select></label>
    <label>Wzór numeru<input name="pattern" value="{$s.pattern|escape}" maxlength="100" required></label>
    <label>Następny numer<input name="next_number" type="number" min="1" max="100000000" value="{$s.next_number}" required></label>
    {if $s.kind eq 'receipt'}<label>Drukarka fiskalna<select name="fiscal_printer_id"><option value="0" {if !$s.effective_printer_id}selected{/if}>Bez automatycznego druku</option>{foreach $printFiscalPrinters as $printer}{if $printer.enabled or $printer.id eq $s.effective_printer_id}<option value="{$printer.id}" {if $printer.id eq $s.effective_printer_id}selected{/if}>{$printer.name|escape} · {$printer.host|escape}:{$printer.port} · {if $printer.enabled}{if $printer.environment eq 'production'}PRODUKCJA{else}SANDBOX{/if}{else}nieaktywna — wybierz inną{/if}</option>{/if}{/foreach}</select></label>{/if}
    {if $canWrite}<button class="om-btn om-small">Zapisz serię</button>{/if}
  </form>
{foreachelse}<p class="om-muted">Dodaj osobne serie dla faktur, paragonów i korekt.</p>{/foreach}
{if $canWrite}<h4 class="om-top">Nowa seria</h4><form class="om-form om-top" method="post" action="?controller=orders&action=save"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="series"><input type="hidden" name="tab" value="documents"><label>Nazwa serii<input name="name" placeholder="Faktury — sklep główny" required></label><label>Typ<select name="kind"><option value="invoice">Faktura</option><option value="receipt">Paragon</option><option value="invoice_correction">Korekta faktury</option><option value="receipt_correction">Korekta paragonu</option></select></label><label>Wzór numeru<input name="pattern" value="FV/{literal}{YYYY}/{MM}/{N}{/literal}" required></label><label>Pierwszy numer<input name="next_number" type="number" min="1" value="1" required></label><label>Drukarka dla serii paragonów<select name="fiscal_printer_id"><option value="0">Bez automatycznego druku</option>{foreach $printFiscalPrinters as $printer}{if $printer.enabled}<option value="{$printer.id}">{$printer.name|escape} · {$printer.host|escape}:{$printer.port}</option>{/if}{/foreach}</select></label><small class="om-muted">Dla faktur i korekt pozostaw „Bez automatycznego druku”. {literal}{N} — kolejny numer · {YYYY} — rok · {MM} — miesiąc.{/literal} Licznik rośnie bez automatycznego resetu.</small><button class="om-btn om-primary">Dodaj serię</button></form>{/if}</section></div>
<section class="om-panel om-top"><div class="om-panel-heading"><h3>Ostatnie dokumenty</h3><span class="om-chip">100 ostatnich</span></div><div class="om-table-wrap"><table class="om-table"><thead><tr><th>Numer</th><th>Typ</th><th>Zamówienie</th><th>Zapisano (UTC)</th><th></th></tr></thead><tbody>{foreach $documents as $d}<tr><td><strong>{$d.number|escape}</strong></td><td>{$d.kind|escape}</td><td><a href="?controller=orders&id={$d.order_id}">#{$d.order_id}</a></td><td>{$d.created_at|escape}</td><td><a class="om-btn om-small" href="?controller=orders&action=printdocument&id={$d.id}" target="_blank" rel="noopener">Podgląd A4 ↗</a></td></tr>{foreachelse}<tr><td colspan="5"><div class="om-empty"><i class="bi bi-file-earmark-text"></i><h3>Pierwszy dokument przed Tobą</h3><p>Uzupełnij sprzedawcę i serię, następnie otwórz zamówienie.</p></div></td></tr>{/foreach}</tbody></table></div></section>
