<link rel="stylesheet" href="dist/css/orders-create.css?v=20260909-1">
<link rel="stylesheet" href="dist/css/orders-cod.css?v=20260909-4">
<main class="app-main om {if $detail}om-order-view{/if}">
{if !isset($shippingDefaults)}{assign var=shippingDefaults value=['default_carrier_account_id'=>0,'default_package'=>'auto','service'=>'auto','apaczka_service_id'=>0,'pickup_type'=>'SELF','presets'=>['small'=>['length'=>23,'width'=>16,'height'=>10,'weight'=>0.5],'medium'=>['length'=>30,'width'=>20,'height'=>15,'weight'=>1],'large'=>['length'=>40,'width'=>30,'height'=>20,'weight'=>2]],'sender'=>['name'=>'','email'=>'','phone'=>'','street'=>'','building'=>'','postal_code'=>'','city'=>'']]}{/if}
{if !isset($shipmentSuggestion)}{assign var=shipmentSuggestion value=['carrier_account_id'=>0,'reason'=>'Wybierz aktywne konto nadawcze','preset'=>'medium','package'=>$shippingDefaults.presets.medium,'service'=>'inpost_locker_standard']}{/if}
{if !isset($documentDefaults)}{assign var=documentDefaults value=['vat'=>'23']}{/if}

<div class="om-shell">
  <header class="om-hero">
    <div><div class="om-eyebrow">SPRZEDAŻ · REALIZACJA</div><h1>Centrum zamówień</h1><p>Jedna kolejka dla wszystkich kanałów sprzedaży.</p></div>
    <div class="om-hero-actions"><span class="om-safe"><i class="bi bi-shield-check"></i> Marketplace: tylko odczyt</span>{if $canWrite}<a class="om-btn om-primary" href="?controller=orders&tab=new"><i class="bi bi-plus-lg"></i> Nowe zamówienie</a><button class="om-btn" type="button" data-sync="test" title="Ponownie odczytaj zamówienia z 7 dni i uzupełnij brakujące miniatury"><i class="bi bi-images"></i> Uzupełnij zdjęcia</button><button class="om-btn" type="button" data-sync="live"><i class="bi bi-arrow-repeat"></i> Synchronizuj</button>{/if}</div>
  </header>
  {if $flashSuccess}<div class="om-alert success">{$flashSuccess|escape}</div>{/if}
  {if $flashError}<div class="om-alert error">{$flashError|escape}</div>{/if}
  <div id="om-sync-result" class="om-alert" hidden role="status" aria-live="polite"></div>
  {if $tab eq 'new'}
    <section class="om-panel om-new-order">
      <div class="om-panel-heading"><div><h2>Nowe zamówienie własne</h2><p>Wprowadź klienta, produkty, walutę i sposób płatności.</p></div><a class="om-btn" href="?controller=orders"><i class="bi bi-x-lg"></i> Anuluj</a></div>
      <form method="post" action="?controller=orders&action=save" data-new-order-form>
        <input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="create_order"><input type="hidden" name="tab" value="new">
        <div class="om-new-grid">
          <fieldset><legend>Klient i status</legend><label>Nazwa klienta<input name="buyer_name" required maxlength="255" autofocus></label><label>E-mail<input type="email" name="email"></label><label>Telefon<input name="phone"></label><label>Data zamówienia<input type="datetime-local" name="ordered_at" value="{$smarty.now|date_format:'%Y-%m-%dT%H:%M'}" required></label><label>Status<select name="status_id" required>{foreach $statuses as $s}<option value="{$s.id}">{$s.name|escape}</option>{/foreach}</select></label></fieldset>
          <fieldset><legend>Dostawa</legend><label>Metoda dostawy<input name="delivery" placeholder="Np. kurier, odbiór osobisty"></label><label>Koszt dostawy<input inputmode="decimal" name="shipping_price" value="0.00" data-new-shipping></label><label>Ulica<input name="shipping_street"></label><label>Nr budynku / lokalu<input name="shipping_building"></label><label>Kod pocztowy<input name="shipping_postal_code"></label><label>Miasto<input name="shipping_city"></label><label>Kraj<select name="shipping_country"><option value="PL">Polska (PL)</option><option value="CZ">Czechy (CZ)</option><option value="HU">Węgry (HU)</option><option value="DE">Niemcy (DE)</option><option value="SK">Słowacja (SK)</option><option value="AT">Austria (AT)</option><option value="RO">Rumunia (RO)</option><option value="GB">Wielka Brytania (GB)</option><option value="US">USA (US)</option></select></label></fieldset>
          <fieldset><legend>Płatność</legend><label>Metoda płatności<select name="payment_method" data-new-payment>{foreach $paymentMethods as $method}{if $method.enabled}<option value="{$method.name|escape}" data-cod="{$method.is_cod}">{$method.name|escape}</option>{/if}{/foreach}</select></label><label>Waluta<select name="currency" data-new-currency required>{foreach ['PLN'=>'PLN — złoty','EUR'=>'EUR — euro','USD'=>'USD — dolar amerykański','GBP'=>'GBP — funt','CZK'=>'CZK — korona czeska','HUF'=>'HUF — forint','CHF'=>'CHF — frank','SEK'=>'SEK — korona szwedzka','NOK'=>'NOK — korona norweska','DKK'=>'DKK — korona duńska','RON'=>'RON — lej','BGN'=>'BGN — lew','UAH'=>'UAH — hrywna'] as $code=>$label}<option value="{$code}">{$label}</option>{/foreach}</select></label><label>Zapłacono<input inputmode="decimal" name="amount_paid" value="0.00"></label><label class="om-check"><input type="checkbox" name="paid" value="1" data-new-paid> Płatność potwierdzona</label><label class="om-check"><input type="checkbox" name="cash_on_delivery" value="1" data-new-cod> Płatność przy odbiorze</label><label>Dokument<select name="document_preference"><option value="receipt">Paragon</option><option value="invoice">Faktura</option></select></label></fieldset>
        </div>
        <fieldset class="om-new-items"><legend>Produkty</legend><div class="om-new-items-head"><span>Dodaj wszystkie pozycje zamówienia. Suma wyliczy się automatycznie.</span><button class="om-btn" type="button" data-add-new-item><i class="bi bi-plus-lg"></i> Dodaj produkt</button></div><div data-new-items><div class="om-new-item"><label>Nazwa produktu<input name="items[0][name]" required></label><label>SKU<input name="items[0][sku]"></label><label>Ilość<input type="number" min="1" max="100000" name="items[0][quantity]" value="1" required data-new-qty></label><label>Cena brutto<input inputmode="decimal" name="items[0][price]" value="0.00" required data-new-price></label><label>VAT<select name="items[0][vat]">{foreach ['23','8','5','0','zw','np'] as $v}<option value="{$v}">{$v}{if $v ne 'zw' and $v ne 'np'}%{/if}</option>{/foreach}</select></label><strong data-new-line-total>0,00 PLN</strong><button class="om-icon-btn" type="button" data-remove-new-item aria-label="Usuń pozycję"><i class="bi bi-trash"></i></button></div></div></fieldset>
        <div class="om-new-footer"><label>Uwagi do zamówienia<textarea name="buyer_note" rows="2"></textarea></label><div><span>Razem</span><strong data-new-total>0,00 PLN</strong><input type="hidden" name="total" value="0.00" data-new-total-input><button class="om-btn om-primary"><i class="bi bi-check2"></i> Utwórz zamówienie</button></div></div>
      </form>
    </section>
  {elseif $tab eq 'list'}
    <div class="om-workspace {if $detail}has-detail{/if}">
      <aside class="om-status-list"><div class="om-label">KOLEJKI ZAMÓWIEŃ</div><a href="?controller=orders" class="{if $filters.status_id eq ''}active{/if}"><span><i class="om-all-dot"></i>Wszystkie</span><b>{$dashboard.total}</b></a>{foreach $dashboard.statuses as $s}<a class="{if $filters.status_id eq $s.id}active{/if}" href="?controller=orders&status_id={$s.id}"><span><i style="background:{$s.color|escape}"></i>{$s.name|escape}</span><b>{$s.total}</b></a>{/foreach}<div class="om-queue-summary"><span><b>{$dashboard.today}</b> dzisiaj</span><span><b>{$dashboard.unpaid}</b> do weryfikacji</span></div><div class="om-sidebar-note"><i class="bi bi-shield-check"></i><p>Statusy są lokalne i nie zmieniają zamówienia w marketplace.</p></div></aside>
      {if !$detail}<section class="om-panel om-order-list">
        <div class="om-list-heading"><div><h2>{if $filters.status_id eq ''}Wszystkie zamówienia{else}{foreach $dashboard.statuses as $s}{if $filters.status_id eq $s.id}{$s.name|escape}{/if}{/foreach}{/if}</h2><p><strong>{$listing.total}</strong> wyników <span>·</span> aktualizowane z połączonych kont</p></div><div class="om-list-heading-actions"><span class="om-result-range">Strona {$listing.page} z {$listing.pages}</span><button class="om-icon-btn" type="button" data-density-toggle title="Zmień gęstość wierszy" aria-label="Zmień gęstość wierszy"><i class="bi bi-text-paragraph"></i></button><button class="om-btn" type="button" data-columns-open><i class="bi bi-layout-three-columns"></i> Kolumny</button></div></div>
        <form class="om-filter-form" method="get"><input type="hidden" name="controller" value="orders"><input type="hidden" name="status_id" value="{$filters.status_id|escape}">
          <div class="om-listbar"><div class="om-search"><i class="bi bi-search"></i><input name="q" value="{$filters.q|escape}" placeholder="Szukaj po numerze, kliencie, e-mailu, telefonie, tagu…" aria-label="Szukaj zamówień"></div><select name="account_id" aria-label="Konto"><option value="">Wszystkie konta</option>{foreach $accounts as $a}<option value="{$a.id}" {if $filters.account_id eq $a.id}selected{/if}>{$a.platform|escape} · {$a.name|escape}</option>{/foreach}</select><button class="om-btn {if $activeFilterCount}is-filtered{/if}" type="button" data-filters-toggle aria-expanded="{if $activeFilterCount}true{else}false{/if}"><i class="bi bi-funnel"></i> Filtry{if $activeFilterCount}<b>{$activeFilterCount}</b>{/if}</button><button class="om-btn om-primary" type="submit"><i class="bi bi-search"></i> Pokaż</button></div>
          <div class="om-filter-drawer {if $activeFilterCount}is-open{/if}" data-filter-drawer>
            <label>Platforma<select name="platform"><option value="">Wszystkie</option>{foreach ['manual'=>'Własne','allegro'=>'Allegro','erli'=>'ERLI','empik'=>'Empik','mediamarkt'=>'MediaMarkt','morele'=>'Morele'] as $value=>$label}<option value="{$value}" {if $filters.platform eq $value}selected{/if}>{$label}</option>{/foreach}</select></label>
            <label>Płatność<select name="paid"><option value="">Dowolna</option><option value="1" {if $filters.paid eq '1'}selected{/if}>Potwierdzona</option><option value="0" {if $filters.paid eq '0'}selected{/if}>Niepotwierdzona</option></select></label>
            <label>Data od<input type="date" name="date_from" value="{$filters.date_from|escape}"></label><label>Data do<input type="date" name="date_to" value="{$filters.date_to|escape}"></label>
            <label>Kwota od<input inputmode="decimal" name="amount_from" value="{$filters.amount_from|escape}" placeholder="0,00"></label><label>Kwota do<input inputmode="decimal" name="amount_to" value="{$filters.amount_to|escape}" placeholder="9999,00"></label>
            <label>Sortowanie<select name="sort"><option value="newest" {if $filters.sort eq 'newest'}selected{/if}>Najnowsze najpierw</option><option value="oldest" {if $filters.sort eq 'oldest'}selected{/if}>Najstarsze najpierw</option><option value="amount_desc" {if $filters.sort eq 'amount_desc'}selected{/if}>Kwota: malejąco</option><option value="amount_asc" {if $filters.sort eq 'amount_asc'}selected{/if}>Kwota: rosnąco</option><option value="buyer" {if $filters.sort eq 'buyer'}selected{/if}>Klient A–Z</option></select></label>
            <div class="om-filter-actions"><a href="?controller=orders{if $filters.status_id ne ''}&status_id={$filters.status_id|escape:'url'}{/if}">Wyczyść filtry</a><button class="om-btn om-primary" type="submit">Zastosuj filtry</button></div>
          </div>
        </form>
        <form method="post" action="?controller=orders&action=save"><input type="hidden" name="csrf" value="{$csrf|escape}">
          {if $canWrite}<div class="om-bulk"><label class="om-select-page"><input type="checkbox" id="om-select-all"> Zaznacz stronę</label><span data-selected-count>0 zaznaczonych</span><span class="om-bulk-separator"></span><select name="status_id" aria-label="Status zaznaczonych">{foreach $statuses as $s}<option value="{$s.id}">{$s.name|escape}</option>{/foreach}</select><button class="om-btn om-small" type="submit" name="operation" value="bulk"><i class="bi bi-arrow-left-right"></i> Zmień status</button><button class="om-btn om-small om-danger-outline" type="submit" name="operation" value="bulk_delete" data-confirm-click="Usunąć zaznaczone zamówienia? Tej operacji nie można cofnąć. Zamówienia z marketplace mogą pojawić się ponownie przy kolejnej synchronizacji, chyba że wcześniej wstrzymasz import konta w zakładce Konta."><i class="bi bi-trash"></i> Usuń zaznaczone</button></div>{/if}
          <div class="om-table-wrap"><table class="om-table om-orders-table" data-configurable-table><thead><tr>{if $canWrite}<th class="om-select-cell"></th>{/if}<th data-col="order">Numer zamówienia</th><th data-col="buyer">Klient</th><th data-col="products">Przedmioty</th><th data-col="amount" class="om-right">Kwota</th><th data-col="status">Status</th><th data-col="payment">Płatność</th><th data-col="delivery">Dostawa</th><th data-col="source">Źródło</th><th data-col="tags">Tagi / notatka</th><th data-col="date">Data złożenia</th></tr></thead><tbody>
          {foreach $listing.rows as $o}<tr>{if $canWrite}<td class="om-select-cell"><input type="checkbox" name="ids[]" value="{$o.id}" aria-label="Zaznacz {$o.external_id|escape}"></td>{/if}
            <td data-col="order"><div class="om-order-cell"><button class="om-star" type="button" aria-label="Oznacz gwiazdką"><i class="bi bi-star"></i></button><div><a class="om-order-number" href="?controller=orders&id={$o.id}">{$o.id}</a><button class="om-external-number" type="button" data-copy-order="{$o.external_id|escape}" title="Kliknij, aby skopiować pełny numer: {$o.external_id|escape}"><i class="bi bi-copy"></i><span>{$o.external_short|escape}</span></button><small><span class="om-market {$o.platform|escape}">{$o.platform|escape}</span> {$o.account_name|escape}</small></div></div></td>
            <td data-col="buyer"><strong class="om-ellipsis">{$o.buyer_name|escape}</strong><a class="om-cell-link om-ellipsis" href="mailto:{$o.email|escape}">{$o.email|escape}</a>{if $o.phone}<small class="om-ellipsis">{$o.phone|escape}</small>{/if}</td>
            <td data-col="products"><div class="om-products">{foreach $o.items as $item}<div class="om-product-line"><span class="om-product-thumb">{if $item.image_url}<img src="{$item.image_url|escape}" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer" data-product-image>{else}<i class="bi bi-box"></i>{/if}</span><span><strong>{$item.quantity}× {$item.name|escape}</strong>{if $item.sku}<small>SKU: {$item.sku|escape}</small>{/if}</span></div>{/foreach}{if $o.item_lines gt 3}<button type="button" class="om-more-products">+ {$o.item_lines-3} więcej</button>{/if}{if $o.item_lines eq 0}<span class="om-muted">Brak pozycji</span>{/if}</div></td>
            <td data-col="amount" class="om-right"><strong class="om-amount">{($o.total_cents/100)|string_format:'%.2f'} {$o.currency|escape}</strong><small>dostawa {($o.shipping_cents/100)|string_format:'%.2f'}</small></td>
            <td data-col="status"><span class="om-status" style="--status:{$o.color|escape}">{$o.status_name|escape}</span><small class="om-ellipsis">{$o.remote_status|escape}</small></td>
            <td data-col="payment">{if $o.cash_on_delivery|default:0}<span class="om-payment is-cod"><i class="bi bi-cash-coin"></i> Pobranie</span>{else}<span class="om-payment {if $o.paid}is-paid{/if}"><i class="bi {if $o.paid}bi-check-circle-fill{else}bi-clock{/if}"></i>{if $o.paid} Opłacone{else} Do weryfikacji{/if}</span>{/if}</td>
            <td data-col="delivery"><strong class="om-ellipsis">{$o.delivery|default:'Brak danych'|escape}</strong>{if $o.pickup}<small class="om-cell-link om-ellipsis">{$o.pickup|escape}</small>{/if}</td>
            <td data-col="source"><span class="om-market {$o.platform|escape}">{$o.platform|escape}</span><small class="om-ellipsis">{$o.account_name|escape}</small></td>
            <td data-col="tags">{if $o.tags}<span class="om-tag">{$o.tags|escape}</span>{/if}{if $o.note}<small class="om-ellipsis">{$o.note|escape}</small>{/if}{if !$o.tags && !$o.note}<span class="om-muted">—</span>{/if}</td>
            <td data-col="date"><strong>{$o.ordered_at|escape}</strong><small>UTC</small></td>
          </tr>{foreachelse}<tr class="om-empty-row"><td colspan="11"><div class="om-empty"><i class="bi bi-inbox"></i><h3>Nie znaleziono zamówień</h3><p>{if $filters.q or $activeFilterCount}Zmień lub wyczyść filtry, aby zobaczyć więcej wyników.{else}Połącz konta i pobierz zamówienia z ostatnich 7 dni.{/if}</p><a class="om-btn om-primary" href="?controller=orders&tab=accounts">Konta i import →</a></div></td></tr>{/foreach}</tbody></table></div>
        </form>
        <div class="om-pagination"><span>{$listing.total} pozycji · 50 na stronę</span><div>{if $listing.page gt 1}<a class="om-icon-btn" aria-label="Poprzednia strona" href="?controller=orders&page={$listing.page-1}{if $listQuery}&{$listQuery|escape}{/if}"><i class="bi bi-chevron-left"></i></a>{/if}<b>{$listing.page}</b>{if $listing.page lt $listing.pages}<a class="om-icon-btn" aria-label="Następna strona" href="?controller=orders&page={$listing.page+1}{if $listQuery}&{$listQuery|escape}{/if}"><i class="bi bi-chevron-right"></i></a>{/if}</div></div>
        <div class="om-columns-backdrop" data-columns-backdrop hidden></div><aside class="om-columns-panel" data-columns-panel aria-hidden="true"><div class="om-columns-head"><div><small>WIDOK LISTY</small><h3>Kolumny i szerokości</h3></div><button class="om-icon-btn" type="button" data-columns-close aria-label="Zamknij"><i class="bi bi-x-lg"></i></button></div><p>Przeciągnij pola, aby zmienić kolejność. Ustawienia zapisują się w tej przeglądarce.</p><div class="om-column-list" data-column-list>
          {foreach ['order'=>'Numer zamówienia','buyer'=>'Klient','products'=>'Przedmioty','amount'=>'Kwota','status'=>'Status','payment'=>'Płatność','delivery'=>'Dostawa','source'=>'Źródło','tags'=>'Tagi / notatka','date'=>'Data złożenia'] as $key=>$label}<div class="om-column-option" draggable="true" data-column-option="{$key}"><i class="bi bi-grip-vertical"></i><label><input type="checkbox" data-column-toggle="{$key}" {if in_array($key,['order','buyer','products','amount','status','date'])}checked{/if}><span>{$label}</span></label><input type="range" min="90" max="420" step="10" value="{if $key eq 'products'}300{elseif $key eq 'buyer'}190{elseif $key eq 'order'}170{elseif $key eq 'date'}150{else}130{/if}" data-column-width="{$key}" aria-label="Szerokość: {$label}"><output></output></div>{/foreach}
        </div><div class="om-columns-footer"><button class="om-btn" type="button" data-columns-reset>Przywróć domyślny</button><button class="om-btn om-primary" type="button" data-columns-close>Gotowe</button></div></aside>
      </section>
      {/if}{if $detail}{include file='orders/detail.tpl'}{/if}
    </div>
  {elseif $tab eq 'accounts'}
    <div class="om-section-heading"><div><h2>Twoje kanały sprzedaży</h2><p>Każde konto ma własny import, kursor i mapowanie statusów.</p></div>{if $canWrite}<form method="post" action="?controller=orders&action=save"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="discover"><input type="hidden" name="tab" value="accounts"><button class="om-btn om-primary">Wczytaj konta z integracji</button></form>{/if}</div>
    <div class="om-alert">Import testowy i bieżący obejmuje wyłącznie zamówienia utworzone w ostatnich 7 dniach. Import testowy zapisuje prawdziwe zamówienia lokalnie. Powtórzenie odświeża dane, bez duplikatów.</div>
    <div class="om-account-grid">{foreach $accounts as $a}<article class="om-panel"><div class="om-panel-heading"><span class="om-market {$a.platform|escape}">{$a.platform|escape}</span><span class="om-chip">{if $a.enabled}Import włączony{else}Import wstrzymany{/if}</span>{if $a.platform eq 'empik' || $a.platform eq 'mediamarkt'}<span class="om-chip{if $a.auto_accept} om-chip-on{/if}">{if $a.auto_accept}Auto-akceptacja: włączona{else}Auto-akceptacja: wyłączona{/if}</span>{/if}</div><div class="om-pad"><h3>{$a.name|escape}</h3><p class="om-muted">Konto źródłowe #{$a.source_id}</p><dl><dt>Ostatni odczyt (UTC)</dt><dd>{$a.last_sync|default:'Jeszcze nie pobierano'|escape}</dd><dt>Kolejka</dt><dd>{if $a.cursor_json}Pozostały kolejne strony{else}Brak oczekujących stron{/if}</dd></dl>{if $a.last_error}<div class="om-alert error">{$a.last_error|escape}</div>{/if}{if $a.platform eq 'morele'}<div class="om-alert">Adapter zamówień Morele oczekuje na specyfikację API. Obecna integracja ofert obsługuje jedno konto.</div>{elseif $canWrite}<div class="om-actions"><form method="post" action="?controller=orders&action=save"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="account"><input type="hidden" name="tab" value="accounts"><input type="hidden" name="account_id" value="{$a.id}"><input type="hidden" name="enabled" value="{if $a.enabled}0{else}1{/if}"><button class="om-btn">{if $a.enabled}Wstrzymaj import{else}Włącz import bieżący{/if}</button></form>{if $a.platform eq 'empik' || $a.platform eq 'mediamarkt'}<form method="post" action="?controller=orders&action=save" title="Automatycznie akceptuje w Mirakl (OR21) każde zamówienie oczekujące na akceptację, gdy tylko trafi do importu."><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="account_auto_accept"><input type="hidden" name="tab" value="accounts"><input type="hidden" name="account_id" value="{$a.id}"><input type="hidden" name="auto_accept" value="{if $a.auto_accept}0{else}1{/if}"><button class="om-btn{if !$a.auto_accept} om-primary{/if}">{if $a.auto_accept}Wyłącz auto-akceptację{else}Włącz auto-akceptację{/if}</button></form>{/if}<button type="button" class="om-btn om-primary" data-sync="test" data-account="{$a.id}">Test: ostatnie 7 dni</button></div>{/if}</div></article>{foreachelse}<div class="om-panel om-empty"><i class="bi bi-plug"></i><h3>Podłącz istniejące integracje</h3><p>Kliknij „Wczytaj konta z integracji”. Klucze API pozostają w ustawieniach platform.</p></div>{/foreach}</div>
    <div class="om-panel om-pad om-top"><h3>Praca w tle</h3><p>Uruchom na serwerze co minutę: <code>php bin/orders-sync.php</code>. Polecenie pobiera jedną stronę na konto w każdym przebiegu; kursor jest zachowywany. W otwartej zakładce dodatkowo działa odczyt co 60 sekund.</p><p class="om-muted">Nowe konta dodawaj w istniejących ustawieniach Allegro, Erli, Empik lub MediaMarkt, następnie wczytaj je tutaj. Tryb odczytu nie zmienia statusów i nie dodaje numerów paczek na platformach. Jedyny wyjątek to opcjonalna auto-akceptacja zamówień Empik/MediaMarkt włączana osobno dla każdego konta poniżej.</p></div>
  {elseif $tab eq 'statuses'}
    <div class="om-section-heading"><div><h2>Statusy na Twoich zasadach</h2><p>Mapowanie działa przy imporcie. Ręczna zmiana statusu chroni go przed nadpisaniem przez synchronizację.</p></div></div>
    <div class="om-two-col"><section class="om-panel om-pad"><h3>Statusy wewnętrzne</h3>{foreach $statuses as $s}<form class="om-inline-form" method="post" action="?controller=orders&action=save"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="status"><input type="hidden" name="tab" value="statuses"><input type="hidden" name="status_id" value="{$s.id}"><input type="color" name="color" value="{$s.color|escape}" aria-label="Kolor"><input name="name" value="{$s.name|escape}" required aria-label="Nazwa statusu"><input type="number" name="position" value="{$s.position}" class="om-position" aria-label="Kolejność">{if $canWrite}<button class="om-btn">Zapisz</button>{/if}</form>{/foreach}{if $canWrite}<h4 class="om-top">Nowy status</h4><form class="om-inline-form" method="post" action="?controller=orders&action=save"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="status"><input type="hidden" name="tab" value="statuses"><input type="color" name="color" value="#6366f1" aria-label="Kolor nowego statusu"><input name="name" placeholder="Np. Czeka na dostawę" required><input type="number" name="position" value="10" class="om-position" aria-label="Kolejność"><button class="om-btn om-primary">Dodaj</button></form>{/if}</section>
    <section class="om-panel om-pad"><h3>Platforma → status wewnętrzny</h3>{if $canWrite}<form class="om-form" method="post" action="?controller=orders&action=save"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="mapping"><input type="hidden" name="tab" value="statuses"><label>Konto<select name="account_id" required>{foreach $accounts as $a}<option value="{$a.id}">{$a.platform|escape} · {$a.name|escape}</option>{/foreach}</select></label><label>Status źródłowy<input name="remote_status" required placeholder="Np. READY_FOR_PROCESSING lub purchased"></label><label>Status wewnętrzny<select name="status_id">{foreach $statuses as $s}<option value="{$s.id}">{$s.name|escape}</option>{/foreach}</select></label><button class="om-btn om-primary">Zapisz mapowanie</button></form>{/if}{foreach $mappings as $m}<div class="om-mapping"><div><small>{$m.platform|escape} · {$m.account_name|escape}</small><p><code>{$m.remote_status|escape}</code> → <strong>{$m.status_name|escape}</strong></p></div>{if $canWrite}<form method="post" action="?controller=orders&action=save"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="unmap"><input type="hidden" name="tab" value="statuses"><input type="hidden" name="mapping_id" value="{$m.id}"><button class="om-btn om-small">Usuń</button></form>{/if}</div>{foreachelse}<p class="om-muted om-top">Bez mapowania zamówienia trafiają do statusu „Nowe”.</p>{/foreach}</section></div>
  {elseif $tab eq 'rules'}
    <div class="om-section-heading"><div><h2>Mniej klikania. Więcej zrobione.</h2><p>Ułóż własne reguły: zdarzenie → warunki → akcje lokalne.</p></div><span class="om-chip">Bez wysyłania zmian do platform</span></div>
    <div class="om-two-col"><section class="om-panel om-pad"><h3>Twoje automatyzacje</h3>{foreach $rules as $r}<article class="om-rule"><div class="om-rule-icon"><i class="bi bi-lightning-charge"></i></div><div><h4>{$r.name|escape}</h4><small>{if $r.trigger_name eq 'import'}Import / odświeżenie zamówienia{else}Ręczna zmiana statusu{/if} · {if $r.enabled}aktywna{else}wstrzymana{/if}</small><p class="om-muted">Warunki: {$r.conditions_label|escape}<br>Akcje: {$r.actions_label|escape}</p>{if $canWrite}<form method="post" action="?controller=orders&action=save"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="toggle_rule"><input type="hidden" name="tab" value="rules"><input type="hidden" name="rule_id" value="{$r.id}"><input type="hidden" name="enabled" value="{if $r.enabled}0{else}1{/if}"><button class="om-btn om-small">{if $r.enabled}Wstrzymaj{else}Włącz{/if}</button></form>{/if}</div></article>{foreachelse}<div class="om-empty"><i class="bi bi-lightning-charge"></i><h3>Stwórz pierwszą regułę</h3><p>Na przykład: po potwierdzeniu płatności<br>przenieś zamówienie do pakowania i dodaj tag.</p></div>{/foreach}</section>
    {if $canWrite}<section class="om-panel om-pad"><h3>Nowa automatyzacja</h3><form class="om-form" method="post" action="?controller=orders&action=save"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="rule"><input type="hidden" name="tab" value="rules"><label>Nazwa reguły<input name="name" required placeholder="Opłacone → do pakowania"></label><div class="om-step">01 · KIEDY</div><label>Zdarzenie<select name="trigger_name"><option value="import">Import / odświeżenie zamówienia</option><option value="status">Ręczna zmiana statusu</option></select></label><div class="om-step">02 · JEŻELI — WSZYSTKIE WARUNKI</div><label>Konto<select name="when_account_id"><option value="">Dowolne</option>{foreach $accounts as $a}<option value="{$a.id}">{$a.platform|escape} · {$a.name|escape}</option>{/foreach}</select></label><label>Status<select name="when_status_id"><option value="">Dowolny</option>{foreach $statuses as $s}<option value="{$s.id}">{$s.name|escape}</option>{/foreach}</select></label><label>Płatność<select name="when_paid"><option value="">Dowolna</option><option value="1">Potwierdzona</option><option value="0">Niepotwierdzona</option></select></label><div class="om-step">03 · WYKONAJ</div><label>Zmień status<select name="then_status_id"><option value="">Nie zmieniaj</option>{foreach $statuses as $s}<option value="{$s.id}">{$s.name|escape}</option>{/foreach}</select></label><label>Dodaj tag<input name="then_tag" placeholder="Np. priorytet"></label><label>Dodaj wpis do historii<input name="then_note" placeholder="Np. Zamówienie gotowe do kompletacji"></label><p class="om-muted">Reguła importu wykona się raz na zamówienie, gdy warunki zostaną spełnione. Akcje nie uruchamiają kolejnych reguł. Test dopasowania jest w szczegółach zamówienia.</p><button class="om-btn om-primary">Utwórz i włącz regułę</button></form></section>{/if}</div>
  {elseif $tab eq 'payments'}
    {include file='orders/payments.tpl'}
  {elseif $tab eq 'documents'}
    {include file='orders/documents.tpl'}
  {elseif $tab eq 'printing'}
    {include file='orders/printing.tpl'}
  {elseif $tab eq 'shipments'}
    <div class="om-section-heading"><div><h2>Przesyłki pod kontrolą</h2><p>Wysyłam z Allegro, InPost ShipX i Apaczka od Alsendo w jednym stanowisku.</p></div><span class="om-chip">{$carrierAccounts|count} skonfigurowanych kont</span></div>
    <section class="om-panel om-shipping-defaults">
      <div class="om-preset-heading"><div><span class="om-preset-icon"><i class="bi bi-magic"></i></span><div><small>AUTOMATYCZNE PODPOWIEDZI</small><h3>Domyślne nadawanie i gabaryty</h3><p>Te ustawienia wypełniają formularz w zamówieniu. Nadal możesz zmienić każdą wartość przed nadaniem.</p></div></div><span class="om-chip">Globalne</span></div>
      {if $canWrite}<form method="post" action="index.php?controller=orders&action=save" class="om-preset-form"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="shipping_defaults"><input type="hidden" name="tab" value="shipments">
        <div class="om-preset-general"><label>Domyślna zawartość przesyłki<input name="shipment_content" maxlength="180" value="{$shippingDefaults.content|default:'Towar'|escape}" required><small>Numer zamówienia zostanie dopisany automatycznie przy nadaniu.</small></label><label>Konto bankowe dla pobrań<input name="cod_bank_account" inputmode="numeric" autocomplete="off" maxlength="30" value="{$shippingDefaults.cod_bank_account|default:''|escape}" placeholder="PL00 0000 0000 0000 0000 0000 0000"><small>Apaczka przeleje pobranie na ten rachunek.</small></label></div>
        <div class="om-preset-general"><label>Domyślne konto nadawcze<select name="default_carrier_account_id"><option value="0">Dobieraj automatycznie</option>{foreach $carrierAccounts as $c}{if $c.enabled}<option value="{$c.id}" {if ($shippingDefaults.default_carrier_account_id|default:0) eq $c.id}selected{/if}>{$c.name|escape}</option>{/if}{/foreach}</select></label><label>Domyślny rozmiar<select name="default_package"><option value="auto" {if ($shippingDefaults.default_package|default:'auto') eq 'auto'}selected{/if}>Automatycznie wg liczby produktów</option><option value="small" {if $shippingDefaults.default_package eq 'small'}selected{/if}>Mała paczka</option><option value="medium" {if $shippingDefaults.default_package eq 'medium'}selected{/if}>Średnia paczka</option><option value="large" {if $shippingDefaults.default_package eq 'large'}selected{/if}>Duża paczka</option></select></label><label>Usługa InPost<select name="service"><option value="auto" {if ($shippingDefaults.service|default:'auto') eq 'auto'}selected{/if}>Automatycznie: Paczkomat lub kurier</option><option value="inpost_locker_standard" {if $shippingDefaults.service eq 'inpost_locker_standard'}selected{/if}>Paczkomat standard</option><option value="inpost_courier_standard" {if $shippingDefaults.service eq 'inpost_courier_standard'}selected{/if}>Kurier standard</option></select></label><label>Domyślny VAT dokumentów<select name="default_vat">{foreach ['23','8','5','0','zw','np'] as $v}<option value="{$v}" {if ($documentDefaults.vat|default:'23') eq $v}selected{/if}>{$v}{if $v ne 'zw' and $v ne 'np'}%{/if}</option>{/foreach}</select></label></div>
        <div class="om-preset-cards">{foreach ['small'=>'Mała','medium'=>'Średnia','large'=>'Duża'] as $key=>$label}<article><h4><i class="bi bi-box"></i> {$label}</h4><div><label>Dł.<input type="number" name="{$key}_length" min="1" max="400" value="{$shippingDefaults.presets[$key].length|default:30}" required><span>cm</span></label><label>Szer.<input type="number" name="{$key}_width" min="1" max="400" value="{$shippingDefaults.presets[$key].width|default:20}" required><span>cm</span></label><label>Wys.<input type="number" name="{$key}_height" min="1" max="400" value="{$shippingDefaults.presets[$key].height|default:15}" required><span>cm</span></label><label>Waga<input type="number" name="{$key}_weight" min="0.01" max="1000" step="0.01" value="{$shippingDefaults.presets[$key].weight|default:1}" required><span>kg</span></label></div></article>{/foreach}</div>
        <details class="om-preset-advanced"><summary>Dane Apaczki, nadawcy i odbioru</summary><div class="om-preset-general"><label>ID usługi Apaczka<input type="number" name="apaczka_service_id" min="0" value="{$shippingDefaults.apaczka_service_id|default:0}"></label><label>Sposób nadania<select name="pickup_type"><option value="SELF" {if ($shippingDefaults.pickup_type|default:'SELF') eq 'SELF'}selected{/if}>Nadaję samodzielnie</option><option value="COURIER" {if $shippingDefaults.pickup_type eq 'COURIER'}selected{/if}>Odbiór przez kuriera</option></select></label><label>Domyślny punkt odbioru / Paczkomat<input name="default_point" value="{$shippingDefaults.default_point|default:''|escape}"></label><label>Nadawca<input name="sender_name" value="{$shippingDefaults.sender.name|default:''|escape}" required></label><label>E-mail<input type="email" name="sender_email" value="{$shippingDefaults.sender.email|default:''|escape}" required></label><label>Telefon<input name="sender_phone" value="{$shippingDefaults.sender.phone|default:''|escape}" pattern="\+?[0-9 ()-]+" minlength="9" maxlength="24" required></label><label>Ulica<input name="sender_street" value="{$shippingDefaults.sender.street|default:''|escape}" required></label><label>Numer<input name="sender_building" value="{$shippingDefaults.sender.building|default:''|escape}" required></label><label>Kod pocztowy<input name="sender_postal_code" value="{$shippingDefaults.sender.postal_code|default:''|escape}" required></label><label>Miasto<input name="sender_city" value="{$shippingDefaults.sender.city|default:''|escape}" required></label></div></details>
        <div class="om-preset-footer"><span><i class="bi bi-info-circle"></i> Konto zgodne ze źródłem zamówienia ma pierwszeństwo przed ustawieniem domyślnym.</span><button class="om-btn om-primary"><i class="bi bi-check2"></i> Zapisz podpowiedzi</button></div>
      </form>{/if}
    </section>
    <div class="om-carrier-grid">
      <article class="om-panel om-pad"><div class="om-carrier-title"><span class="om-carrier-logo allegro">A</span><div><h3>Wysyłam z Allegro</h3><p>Używa autoryzacji konkretnego konta Allegro.</p></div></div>{foreach $carrierAccounts as $c}{if $c.provider eq 'allegro_wza'}<div class="om-connected">● {$c.name|escape} · podłączone</div>{/if}{/foreach}{if $canWrite}<form class="om-form" method="post" action="index.php?controller=orders&action=save"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="carrier_account"><input type="hidden" name="tab" value="shipments"><input type="hidden" name="provider" value="allegro_wza"><label>Nazwa połączenia<input name="name" value="Wysyłam z Allegro" required></label><label>Konto Allegro<select name="allegro_account_id" required><option value="">Wybierz konto</option>{foreach $accounts as $a}{if $a.platform eq 'allegro'}<option value="{$a.id}">{$a.name|escape}</option>{/if}{/foreach}</select></label><button class="om-btn om-primary">Podłącz konto</button></form>{/if}</article>
      <article class="om-panel om-pad"><div class="om-carrier-title"><span class="om-carrier-logo inpost">I</span><div><h3>InPost ShipX</h3><p>Bezpośrednie nadawanie przez organizację ShipX.</p></div></div>{foreach $carrierAccounts as $c}{if $c.provider eq 'inpost_shipx'}<div class="om-connected">● {$c.name|escape} · podłączone</div>{/if}{/foreach}{if $canWrite}<form class="om-form" method="post" action="index.php?controller=orders&action=save" autocomplete="off"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="carrier_account"><input type="hidden" name="tab" value="shipments"><input type="hidden" name="provider" value="inpost_shipx"><label>Nazwa połączenia<input name="name" value="InPost ShipX" required></label><label>ID organizacji<input name="organization_id" required></label><label>Token ShipX<input type="password" name="token" required autocomplete="new-password"></label><label>Środowisko<select name="environment"><option value="production">Produkcyjne</option><option value="sandbox">Sandbox</option></select></label><button class="om-btn om-primary">Zapisz szyfrowane dane</button></form>{/if}</article>
      <article class="om-panel om-pad"><div class="om-carrier-title"><span class="om-carrier-logo apaczka">AP</span><div><h3>Apaczka / Alsendo</h3><p>Web API v2 z kluczami aplikacji.</p></div></div>{foreach $carrierAccounts as $c}{if $c.provider eq 'apaczka'}<div class="om-connected">● {$c.name|escape} · podłączone</div>{/if}{/foreach}{if $canWrite}<form class="om-form" method="post" action="index.php?controller=orders&action=save" autocomplete="off"><input type="hidden" name="csrf" value="{$csrf|escape}"><input type="hidden" name="operation" value="carrier_account"><input type="hidden" name="tab" value="shipments"><input type="hidden" name="provider" value="apaczka"><label>Nazwa połączenia<input name="name" value="Apaczka" required></label><label>App ID<input name="app_id" required></label><label>App Secret<input type="password" name="app_secret" required autocomplete="new-password"></label><button class="om-btn om-primary">Zapisz szyfrowane dane</button></form>{/if}</article>
    </div>
    <div class="om-alert om-top">Dane dostępowe są szyfrowane. Utworzenie przesyłki zawsze wymaga potwierdzenia w konkretnym zamówieniu.</div>
    <section class="om-panel om-top"><table class="om-table"><thead><tr><th>Zamówienie</th><th>Przewoźnik</th><th>Numer przesyłki</th><th>Waga</th><th>Utworzono (UTC)</th></tr></thead><tbody>{foreach $shipments as $p}<tr><td><a href="?controller=orders&id={$p.order_id}">#{$p.order_id}</a></td><td>{$p.carrier|escape}</td><td>{$p.tracking|escape}</td><td>{$p.weight|escape} kg</td><td>{$p.created_at|escape}</td></tr>{foreachelse}<tr><td colspan="5"><div class="om-empty"><i class="bi bi-box-seam"></i><h3>Jeszcze żadna paczka nie trafiła do rejestru</h3><p>Otwórz zamówienie, aby rozpocząć przygotowanie przesyłki.</p></div></td></tr>{/foreach}</tbody></table></section>
  {/if}
</div>
<div id="om-config" data-csrf="{$csrf|escape}" data-write="{if $canWrite}1{else}0{/if}" hidden></div>
<script src="dist/js/orders.js?v=20260916-3" defer></script>
</main>
