<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{$document.number|escape}</title><style>{literal}
*{box-sizing:border-box}body{margin:0;background:#e9edf3;color:#172036;font:13px Arial,sans-serif}.toolbar{max-width:210mm;margin:20px auto;display:flex;justify-content:space-between;align-items:center}.toolbar a,.toolbar button{color:#fff;background:#263c78;border:0;padding:12px 18px;border-radius:8px;text-decoration:none;cursor:pointer}.sheet{width:210mm;min-height:297mm;padding:18mm;margin:0 auto 30px;background:white;box-shadow:0 10px 40px #17203618}.head{display:flex;justify-content:space-between;border-bottom:3px solid #263c78;padding-bottom:24px;gap:24px}h1{font-size:25px;margin:0 0 10px}h2{font-size:13px;text-transform:uppercase;color:#59667b;margin-top:0}.number{font-size:18px}.muted{color:#667085}.parties{display:grid;grid-template-columns:1fr 1fr;gap:35px;margin:30px 0;line-height:1.6}.pre{white-space:pre-line;overflow-wrap:anywhere}table{width:100%;border-collapse:collapse;margin:20px 0}th{text-align:left;background:#eff2f7;font-size:11px;padding:10px 5px}td{border-bottom:1px solid #e3e7ef;padding:12px 5px;overflow-wrap:anywhere}td:nth-child(n+3),th:nth-child(n+3){text-align:right}.totals{margin-left:auto;width:260px;padding:15px;background:#f3f5f9}.totals div{display:flex;justify-content:space-between;margin:8px 0}.total{font-size:20px;font-weight:bold;border-top:1px solid #ccd3df;padding-top:14px}.notice{border:1px solid #d4dbe5;padding:12px;margin-top:24px;font-size:11px;line-height:1.5}footer{margin-top:30px;border-top:1px solid #e3e7ef;padding-top:15px;font-size:11px;color:#667085}tr,.totals,.parties{break-inside:avoid}thead{display:table-header-group}@page{size:A4;margin:15mm}@media print{body{background:white}.toolbar{display:none}.sheet{margin:0;padding:0;width:auto;min-height:0;box-shadow:none}}@media(max-width:820px){.sheet{width:100%;padding:20px}.toolbar{padding:0 15px}.parties{gap:15px}}
{/literal}</style></head><body>
<div class="toolbar"><a href="?controller=orders&id={$document.order_id}">← Zamówienie</a><button onclick="window.print()">Drukuj / zapisz PDF</button></div>
{assign var=d value=$document.snapshot}
<article class="sheet"><div class="head"><div><h1>{if $document.kind eq 'invoice'}Faktura{elseif $document.kind eq 'invoice_correction'}Faktura korygująca{elseif $document.kind eq 'receipt_correction'}Korekta paragonu — niefiskalna{else}Paragon — niefiskalny{/if}</h1><div class="number">{$document.number|escape}</div></div><div class="muted">Data wystawienia: {$d.issue_date|escape}<br>Data sprzedaży: {$d.sale_date|escape}<br>Zamówienie: {$d.order_number|escape}</div></div>
<div class="parties"><section><h2>Sprzedawca</h2><strong>{$d.seller.name|escape}</strong><div class="pre">{$d.seller.address|escape}</div>NIP: {$d.seller.nip|escape}</section><section><h2>Nabywca</h2><div class="pre">{$d.buyer|escape}</div></section></div>
{if isset($d.parent_number)}<p><strong>Korekta do dokumentu:</strong> {$d.parent_number|escape}</p><p><strong>Przyczyna:</strong> {$d.reason|escape}</p><h2>Przed korektą (ostatni zapisany stan)</h2><div class="pre">Nabywca: {$d.before.buyer|escape}</div><table><thead><tr><th>Pozycja</th><th>Ilość</th><th>Netto</th><th>VAT</th><th>Brutto</th></tr></thead><tbody>{foreach $d.before.items as $item}<tr><td>{$item.name|escape}</td><td>{$item.quantity}</td><td>{($item.net_cents/100)|string_format:'%.2f'}</td><td>{($item.tax_cents/100)|string_format:'%.2f'}</td><td>{($item.gross_cents/100)|string_format:'%.2f'}</td></tr>{/foreach}</tbody></table><h2>Po korekcie</h2>{/if}
<table><thead><tr><th>Lp.</th><th>Nazwa towaru / usługi</th><th>Ilość</th><th>Cena brutto</th><th>VAT</th><th>Netto</th><th>Kwota VAT</th><th>Brutto</th></tr></thead><tbody>{foreach $d.items as $i=>$item}<tr><td>{$i+1}</td><td>{$item.name|escape}</td><td>{$item.quantity}</td><td>{($item.unit_cents/100)|string_format:'%.2f'}</td><td>{$item.vat|escape}{if $item.vat ne 'zw' and $item.vat ne 'np'}%{/if}</td><td>{($item.net_cents/100)|string_format:'%.2f'}</td><td>{($item.tax_cents/100)|string_format:'%.2f'}</td><td>{($item.gross_cents/100)|string_format:'%.2f'}</td></tr>{/foreach}</tbody></table>
<div class="totals"><div><span>Netto</span><strong>{($d.net_cents/100)|string_format:'%.2f'} {$d.currency|escape}</strong></div><div><span>VAT</span><strong>{($d.tax_cents/100)|string_format:'%.2f'} {$d.currency|escape}</strong></div><div class="total"><span>Brutto</span><span>{($d.gross_cents/100)|string_format:'%.2f'} {$d.currency|escape}</span></div>{if isset($d.difference_cents)}<div><span>Różnica korekty</span><strong>{($d.difference_cents/100)|string_format:'%.2f'} {$d.currency|escape}</strong></div>{/if}</div>
{if $d.seller.bank}<p>Rachunek bankowy: {$d.seller.bank|escape}</p>{/if}
<div class="notice">Dokument z lokalnego obiegu sprzedaży. Nie wysłano do KSeF.{if $document.kind eq 'receipt' or $document.kind eq 'receipt_correction'} Dokument niefiskalny — nie zastępuje paragonu z urządzenia fiskalnego.{/if}</div><footer>ALTREO · Centrum zamówień · {$document.number|escape}</footer>
</article></body></html>
